modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/PatchouliProvider/issues"
license = "MIT"

[[mods]]
    modId="patchouli_provider"
    version="${file.jarVersion}"
    displayName="Patchouli Provider"
    authors="SkySom, DivineAspect"
    description='''

    '''